# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85524d97c38bd40273b347b694d9af1adee2bffae32e87edb1307cff4c3a1646780a0c7432978ce3099388790c5c75c7da73e5401a22f8b772d744e531eebdfb

test:
  secret_key_base: 4911e7570da33d1ea680929edc00eafae97ffe80e95e1394256d0405e003f2e78527400b28b2c96ce1d4dfa757d6dc2db4b4be7a80daaff1b7847cb6d2012dcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
